version: "3.9"

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ECCEPT_EULA=Y
      - SA_PASSWORD=97072253
    restart: always
  server:
    depends_on:
      - sqldb
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
      - "8081:5001"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/companyemployees.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/